class Languages:
    frases = {
        "ru": {
            "GetOptions": "Выберите опцию: ",
            "GetMode": "1: Получить файл \n2: Отправить файл",
            "GetPathFile": "Введите путь до места отправочного файла просто нажмите 'Enter' для загрузки из \"файла: \"",
            "ServerStarted": "Сервер запущен на %s:%s. Ожидание подключения...",
            "ConnectedTo": "Подключено к %s",
            "DataTransferComplete": "Передача данных завершена.",
            "ReceivedDataWeight": "вес полученных пакетов %sБайт.",
            "LoadingTime": "Время загрузки: %s секунд",
            "HashCheck": "Проверка хэша: %s",
            "ChooseOption": "Выберите опцию: ",
            "ClientLoading": "Загрузка клиента: ...",
            "EnterSavePath": "Введите путь до места сохранения полученного файла просто нажмите 'Enter' для загрузки из \"файла: \"",
            "EnterServerIP": "Введите IP адрес сервера просто нажмите 'Enter' для загрузки из файла: ",
            "EnterMainPort": "Введите главный порт сервера просто нажмите 'Enter' для загрузки из файла: ",
            "ServerLoading": "Загрузка сервера: ...",
            "EnterSendFilePath": "Введите путь до места отправочного файла просто нажмите 'Enter' для загрузки из \"файла: \"",
            "EnterServerLocationIP": "Введите IP адрес расположения сервера в сети просто нажмите 'Enter' для загрузки из файла: ",
            "EnterMaxPorts": "Введите максимальное кол-во портов для соединения просто нажмите 'Enter' для загрузки из файла: ",
            "EnterMaxPacketSize": "Введите максимальный размер пакета просто нажмите 'Enter' для загрузки из файла: ",
            "FilePath": "Путь до файла: %s",
            "MaxPorts": "Максимальное количество портов: %s",
            "HostIP": "IP хоста: %s",
            "HostPort": "Порт хоста: %s",
            "PacketSize": "Размер пакета: %s",
            "AllPackagesSent": "Все пакеты отправлены.",
            "TransferTime": "Время передачи: %s секунд",
            "TransferSpeed": "Скорость передачи: %sБайт/сек",
            "Preparing": "Подготовка...",
            "GettingFileWeight": "Получение веса файла",
            "CountingFileHash": "Подсчёт хэша файла",
            "ClearingCache": "Очистка кэша",
            "DataWeight": "Вес данных %sайт.",
            "BlocksCount": "Количество блоков: ",
            "DataTransferSpeed": "Скорость загрузки: %sБайт/сек",
            "MergingSpeed": "Скорость объединения: %sБайт/сек",
            "DataReceivedWeight": "вес полученных пакетов %sБайт."
        },
        "en": {
            "GetOptions": "Choose an option: ",
            "GetMode": "1: Get file\n2: Send file",
            "GetPathFile": "Enter the path to the sending file, just press 'Enter' to load from \"file: \"",
            "ServerStarted": "Server started on %s:%s. Waiting for connection...",
            "ConnectedTo": "Connected to %s",
            "DataTransferComplete": "Data transfer complete.",
            "ReceivedDataWeight": "Weight of received packets %sBytes.",
            "LoadingTime": "Loading time: %s seconds",
            "HashCheck": "Hash check: %s",
            "ChooseOption": "Choose an option: ",
            "ClientLoading": "Client loading: ...",
            "EnterSavePath": "Enter the path to save the received file, just press 'Enter' to load from \"file: \"",
            "EnterServerIP": "Enter the server IP address, just press 'Enter' to load from file: ",
            "EnterMainPort": "Enter the main server port, just press 'Enter' to load from file: ",
            "ServerLoading": "Server loading: ...",
            "EnterSendFilePath": "Enter the path to the sending file, just press 'Enter' to load from \"file: \"",
            "EnterServerLocationIP": "Enter the server location IP address in the network, just press 'Enter' to load from file: ",
            "EnterMaxPorts": "Enter the maximum numByteser of ports for connection, just press 'Enter' to load from file: ",
            "EnterMaxPacketSize": "Enter the maximum packet size, just press 'Enter' to load from file: ",
            "FilePath": "File path: %s",
            "MaxPorts": "Maximum numByteser of ports: %s",
            "HostIP": "Host IP: %s",
            "HostPort": "Host port: %s",
            "PacketSize": "Packet size: %s",
            "AllPackagesSent": "All packages sent.",
            "TransferTime": "Transfer time: %s seconds",
            "TransferSpeed": "Transfer speed: %sBytes/s",
            "Preparing": "Preparing...",
            "GettingFileWeight": "Getting file weight",
            "CountingFileHash": "Counting file hash",
            "ClearingCache": "Clearing cache",
            "DataWeight": "Data weight %sBytesytes.",
            "BlocksCount": "NumByteser of Byteslocks: ",
            "DataTransferSpeed": "Upload speed: %sBytes/s",
            "MergingSpeed": "Merging speed: %sBytes/s",
            "DataReceivedWeight": "Weight of received packets %sBytes."
        },
        "it": {
            "GetOptions": "Scegli un'opzione: ",
            "GetMode": "1: Ottieni file \n2: Invia file",
            "GetPathFile": "Inserisci il percorso del file da inviare, premi 'Invio' per caricare da \"file: \"",
            "ServerStarted": "Server avviato su %s:%s. In attesa di connessione...",
            "ConnectedTo": "Connesso a %s",
            "DataTransferComplete": "Trasferimento dati completato.",
            "ReceivedDataWeight": "Peso dei pacchetti ricevuti %sBytes.",
            "LoadingTime": "Tempo di caricamento: %s secondi",
            "HashCheck": "Controllo hash: %s",
            "ChooseOption": "Scegli un'opzione: ",
            "ClientLoading": "Caricamento client: ...",
            "EnterSavePath": "Inserisci il percorso per salvare il file ricevuto, premi 'Invio' per caricare da \"file: \"",
            "EnterServerIP": "Inserisci l'indirizzo IP del server, premi 'Invio' per caricare dal file: ",
            "EnterMainPort": "Inserisci la porta principale del server, premi 'Invio' per caricare dal file: ",
            "ServerLoading": "Caricamento server: ...",
            "EnterSendFilePath": "Inserisci il percorso del file da inviare, premi 'Invio' per caricare da \"file: \"",
            "EnterServerLocationIP": "Inserisci l'indirizzo IP della posizione del server nella rete, premi 'Invio' per caricare dal file: ",
            "EnterMaxPorts": "Inserisci il numero massimo di porte per la connessione, premi 'Invio' per caricare dal file: ",
            "EnterMaxPacketSize": "Inserisci la dimensione massima del pacchetto, premi 'Invio' per caricare dal file: ",
            "FilePath": "Percorso del file: %s",
            "MaxPorts": "Numero massimo di porte: %s",
            "HostIP": "IP dell'host: %s",
            "HostPort": "Porta dell'host: %s",
            "PacketSize": "Dimensione del pacchetto: %s",
            "AllPackagesSent": "Tutti i pacchetti inviati.",
            "TransferTime": "Tempo di trasferimento: %s secondi",
            "DataWeight": "Peso dei dati: %sBytes",
            "TransferSpeed": "Velocità di trasferimento: %sBytes/s",
            "Preparing": "Preparazione in corso...",
            "GettingFileWeight": "Ottenimento del peso del file",
            "CountingFileHash": "Calcolo dell'hash del file",
            "ClearingCache": "Cancellazione della cache",
            "DataWeigh": "Peso dei dati %sBytesyte.",
            "BlocksCount": "Numero di Byteslocchi: ",
            "DataTransferSpeed": "Velocità di caricamento: %sBytes/s",
            "MergingSpeed": "Velocità di unione: %sBytes/s",
            "DataReceivedWeight": "Peso dei pacchetti ricevuti %sBytesyte."
        },
        "de": {
            "GetOptions": "Wählen Sie eine Option: ",
            "GetMode": "1: Datei erhalten \n2: Datei senden",
            "GetPathFile": "GeBytesen Sie den Pfad zur zu sendenden Datei ein, drücken Sie einfach 'Enter', um von \"Datei: \" zu laden",
            "ServerStarted": "Server gestartet auf %s:%s. Warte auf VerBytesindung...",
            "ConnectedTo": "VerBytesunden mit %s",
            "DataTransferComplete": "DatenüBytesertragung aBytesgeschlossen.",
            "ReceivedDataWeight": "Gewicht der empfangenen Pakete %sBytes.",
            "LoadingTime": "Ladezeit: %s Sekunden",
            "HashCheck": "Hash-Prüfung: %s",
            "ChooseOption": "Wählen Sie eine Option: ",
            "ClientLoading": "Client wird geladen: ...",
            "EnterSavePath": "GeBytesen Sie den Pfad zum Speichern der empfangenen Datei ein, drücken Sie einfach 'Enter', um von \"Datei: \" zu laden",
            "EnterServerIP": "GeBytesen Sie die IP-Adresse des Servers ein, drücken Sie einfach 'Enter', um von der Datei zu laden: ",
            "EnterMainPort": "GeBytesen Sie den Hauptport des Servers ein, drücken Sie einfach 'Enter', um von der Datei zu laden: ",
            "ServerLoading": "Server wird geladen: ...",
            "EnterSendFilePath": "GeBytesen Sie den Pfad zur zu sendenden Datei ein, drücken Sie einfach 'Enter', um von \"Datei: \" zu laden",
            "EnterServerLocationIP": "GeBytesen Sie die IP-Adresse des Serverstandorts im Netzwerk ein, drücken Sie einfach 'Enter', um von der Datei zu laden: ",
            "EnterMaxPorts": "GeBytesen Sie die maximale Anzahl von Ports für die VerBytesindung ein, drücken Sie einfach 'Enter', um von der Datei zu laden: ",
            "EnterMaxPacketSize": "GeBytesen Sie die maximale Paketgröße ein, drücken Sie einfach 'Enter', um von der Datei zu laden: ",
            "FilePath": "Dateipfad: %s",
            "MaxPorts": "Maximale Anzahl von Ports: %s",
            "HostIP": "Host-IP: %s",
            "HostPort": "Host-Port: %s",
            "PacketSize": "Paketgröße: %s",
            "AllPackagesSent": "Alle Pakete gesendet.",
            "TransferTime": "ÜBytesertragungszeit: %s Sekunden",
            "TransferSpeed": "ÜBytesertragungsgeschwindigkeit: %sBytes/s",
            "Preparing": "VorBytesereitung...",
            "GettingFileWeight": "Gewicht der Datei wird ermittelt",
            "CountingFileHash": "Dateihash wird Byteserechnet",
            "ClearingCache": "Cache wird geleert",
            "DataWeight": "Datengewicht %sBytesytes.",
            "BlocksCount": "Anzahl der Byteslöcke: ",
            "DataTransferSpeed": "Uploadgeschwindigkeit: %sBytes/s",
            "MergingSpeed": "Zusammenführungsgeschwindigkeit: %sBytes/s",
            "DataReceivedWeight": "Gewicht der empfangenen Pakete %sBytesytes."
        },
        "ja": {
            "GetOptions": "オプションを選択してください: ",
            "GetMode": "1: ファイルを取得 \n2: ファイルを送信",
            "GetPathFile": "送信ファイルのパスを入力してください。「ファイル: 」から読み込むには「Enter」を押してください。",
            "ServerStarted": "サーバーは %s:%s で起動しました。接続を待っています...",
            "ConnectedTo": "接続先: %s",
            "DataTransferComplete": "データ転送が完了しました。",
            "ReceivedDataWeight": "受信したパケットの重さ %sBytes。",
            "LoadingTime": "読み込み時間: %s 秒",
            "HashCheck": "ハッシュチェック: %s",
            "ChooseOption": "オプションを選択してください: ",
            "ClientLoading": "クライアントを読み込んでいます: ...",
            "EnterSavePath": "受信したファイルを保存するパスを入力してください。「ファイル: 」から読み込むには「Enter」を押してください。",
            "EnterServerIP": "サーバーのIPアドレスを入力してください。ファイルから読み込むには「Enter」を押してください: ",
            "EnterMainPort": "サーバーのメインポートを入力してください。ファイルから読み込むには「Enter」を押してください: ",
            "ServerLoading": "サーバーを読み込んでいます: ...",
            "EnterSendFilePath": "送信ファイルのパスを入力してください。「ファイル: 」から読み込むには「Enter」を押してください。",
            "EnterServerLocationIP": "ネットワーク内のサーバーの場所のIPアドレスを入力してください。ファイルから読み込むには「Enter」を押してください: ",
            "EnterMaxPorts": "接続のための最大ポート数を入力してください。ファイルから読み込むには「Enter」を押してください: ",
            "EnterMaxPacketSize": "最大パケットサイズを入力してください。ファイルから読み込むには「Enter」を押してください: ",
            "FilePath": "ファイルパス: %s",
            "MaxPorts": "最大ポート数: %s",
            "HostIP": "ホストIP: %s",
            "HostPort": "ホストポート: %s",
            "PacketSize": "パケットサイズ: %s",
            "AllPackagesSent": "すべてのパケットが送信されました。",
            "TransferTime": "転送時間: %s 秒",
            "TransferSpeed": "転送速度: %sBytes/秒",
            "Preparing": "準備中...",
            "GettingFileWeight": "ファイルの重さを取得中",
            "CountingFileHash": "ファイルのハッシュを計算中",
            "ClearingCache": "キャッシュをクリア中",
            "DataWeight": "データの重さ %sBytes",
            "BlocksCount": "ブロック数: ",
            "DataTransferSpeed": "アップロード速度: %sBytes/秒",
            "MergingSpeed": "マージ速度: %sBytes/秒",
            "DataReceivedWeight": "受信したパケットの重さ %sBytes"
        },
        "zh": {
            "GetOptions": "请选择一个选项: ",
            "GetMode": "1: 获取文件 \n2: 发送文件",
            "GetPathFile": "请输入发送文件的路径，直接按 'Enter' 从 \"文件: \" 加载",
            "ServerStarted": "服务器在 %s:%s 启动。等待连接...",
            "ConnectedTo": "已连接到 %s",
            "DataTransferComplete": "数据传输完成。",
            "ReceivedDataWeight": "接收的数据包重量 %sBytes。",
            "LoadingTime": "加载时间: %s 秒",
            "HashCheck": "哈希检查: %s",
            "ChooseOption": "选择一个选项: ",
            "ClientLoading": "客户端加载中: ...",
            "EnterSavePath": "请输入接收文件的保存路径，直接按 'Enter' 从 \"文件: \" 加载",
            "EnterServerIP": "请输入服务器的 IP 地址，直接按 'Enter' 从文件加载: ",
            "EnterMainPort": "请输入服务器的主端口，直接按 'Enter' 从文件加载: ",
            "ServerLoading": "服务器加载中: ...",
            "EnterSendFilePath": "请输入发送文件的路径，直接按 'Enter' 从 \"文件: \" 加载",
            "EnterServerLocationIP": "请输入网络中服务器位置的 IP 地址，直接按 'Enter' 从文件加载: ",
            "EnterMaxPorts": "请输入连接的最大端口数，直接按 'Enter' 从文件加载: ",
            "EnterMaxPacketSize": "请输入最大数据包大小，直接按 'Enter' 从文件加载: ",
            "FilePath": "文件路径: %s",
            "MaxPorts": "最大端口数: %s",
            "HostIP": "主机 IP: %s",
            "HostPort": "主机端口: %s",
            "PacketSize": "数据包大小: %s",
            "AllPackagesSent": "所有数据包已发送。",
            "TransferTime": "传输时间: %s 秒",
            "DataWeight": "数据重量: %sBytes",
            "TransferSpeed": "传输速度: %sBytes/秒",
            "Preparing": "准备中...",
            "GettingFileWeight": "获取文件重量",
            "CountingFileHash": "计算文件哈希",
            "ClearingCache": "清理缓存",
            "BlocksCount": "区块数量: ",
            "DataTransferSpeed": "上传速度: %sBytes/秒",
            "MergingSpeed": "合并速度: %sBytes/秒",
            "DataReceivedWeight": "接收的数据包重量 %sBytes",
            "YouCanDoItBytesetter": "你可以做得更好。",
            "Need": "需要"
        },
        "ko": {
            "GetOptions": "옵션를 선택하세요: ",
            "GetMode": "1: 파일 받기 \n2: 파일 보내기",
            "GetPathFile": "전송할 파일의 경로를 입력하세요. 'Enter'를 눌러 \"파일: \"에서 로드합니다.",
            "ServerStarted": "서버가 %s:%s에서 시작되었습니다. 연결을 기다리는 중...",
            "ConnectedTo": "%s에 연결됨",
            "DataTransferComplete": "데이터 전송이 완료되었습니다.",
            "ReceivedDataWeight": "수신된 패킷의 무게 %sBytes.",
            "LoadingTime": "로딩 시간: %s 초",
            "HashCheck": "해시 확인: %s",
            "ChooseOption": "옵션을 선택하세요: ",
            "ClientLoading": "클라이언트 로딩 중: ...",
            "EnterSavePath": "수신한 파일을 저장할 경로를 입력하세요. 'Enter'를 눌러 \"파일: \"에서 로드합니다.",
            "EnterServerIP": "서버의 IP 주소를 입력하세요. 'Enter'를 눌러 파일에서 로드합니다: ",
            "EnterMainPort": "서버의 주요 포트를 입력하세요. 'Enter'를 눌러 파일에서 로드합니다: ",
            "ServerLoading": "서버 로딩 중: ...",
            "EnterSendFilePath": "전송할 파일의 경로를 입력하세요. 'Enter'를 눌러 \"파일: \"에서 로드합니다.",
            "EnterServerLocationIP": "네트워크에서 서버 위치의 IP 주소를 입력하세요. 'Enter'를 눌러 파일에서 로드합니다: ",
            "EnterMaxPorts": "연결을 위한 최대 포트 수를 입력하세요. 'Enter'를 눌러 파일에서 로드합니다: ",
            "EnterMaxPacketSize": "최대 패킷 크기를 입력하세요. 'Enter'를 눌러 파일에서 로드합니다: ",
            "FilePath": "파일 경로: %s",
            "MaxPorts": "최대 포트 수: %s",
            "HostIP": "호스트 IP: %s",
            "HostPort": "호스트 포트: %s",
            "PacketSize": "패킷 크기: %s",
            "AllPackagesSent": "모든 패킷이 전송되었습니다.",
            "TransferTime": "전송 시간: %s 초",
            "TransferSpeed": "전송 속도: %sBytes/초",
            "Preparing": "준비 중...",
            "GettingFileWeight": "파일 무게를 가져오는 중",
            "CountingFileHash": "파일 해시를 계산하는 중",
            "ClearingCache": "캐시를 지우는 중",
            "DataWeight": "데이터 무게 %sBytes",
            "BlocksCount": "블록 수: ",
            "DataTransferSpeed": "업로드 속도: %sBytes/초",
            "MergingSpeed": "병합 속도: %sBytes/초",
            "DataReceivedWeight": "수신된 패킷의 무게 %sBytes",
            "YouCanDoItBytesetter": "당신은 더 잘할 수 있습니다.",
            "Need": "필요"
        },
        "tr": {
            "GetOptions": "Bytesir seçenek seçin: ",
            "GetMode": "1: Dosyayı al \n2: Dosyayı gönder",
            "GetPathFile": "Gönderilecek dosyanın yolunu girin, \"dosya: \"'dan yüklemek için 'Enter' tuşuna Bytesasın",
            "ServerStarted": "Sunucu %s:%s adresinde Bytesaşlatıldı. Bytesağlantı Bytesekleniyor...",
            "ConnectedTo": "%s ile Bytesağlantı kuruldu",
            "DataTransferComplete": "Veri transferi tamamlandı.",
            "ReceivedDataWeight": "Alınan paketlerin ağırlığı %s GBytes.",
            "LoadingTime": "Yükleme süresi: %s saniye",
            "HashCheck": "Hash kontrolü: %s",
            "ChooseOption": "Bytesir seçenek seçin: ",
            "ClientLoading": "İstemci yükleniyor: ...",
            "EnterSavePath": "Alınan dosyanın kaydedileceği yolu girin, \"dosya: \"'dan yüklemek için 'Enter' tuşuna Bytesasın",
            "EnterServerIP": "Sunucunun IP adresini girin, dosyadan yüklemek için 'Enter' tuşuna Bytesasın: ",
            "EnterMainPort": "Sunucunun ana portunu girin, dosyadan yüklemek için 'Enter' tuşuna Bytesasın: ",
            "ServerLoading": "Sunucu yükleniyor: ...",
            "EnterSendFilePath": "Gönderilecek dosyanın yolunu girin, \"dosya: \"'dan yüklemek için 'Enter' tuşuna Bytesasın",
            "EnterServerLocationIP": "Ağdaki sunucu konumunun IP adresini girin, dosyadan yüklemek için 'Enter' tuşuna Bytesasın: ",
            "EnterMaxPorts": "Bytesağlantı için maksimum port sayısını girin, dosyadan yüklemek için 'Enter' tuşuna Bytesasın: ",
            "EnterMaxPacketSize": "Maksimum paket Bytesoyutunu girin, dosyadan yüklemek için 'Enter' tuşuna Bytesasın: ",
            "FilePath": "Dosya yolu: %s",
            "MaxPorts": "Maksimum port sayısı: %s",
            "HostIP": "Ana Bytesilgisayar IP'si: %s",
            "HostPort": "Ana Bytesilgisayar portu: %s",
            "PacketSize": "Paket Bytesoyutu: %s",
            "AllPackagesSent": "Tüm paketler gönderildi.",
            "TransferTime": "Transfer süresi: %s saniye",
            "TransferSpeed": "Transfer hızı: %sBytes/sn",
            "Preparing": "Hazırlanıyor...",
            "GettingFileWeight": "Dosya ağırlığı alınıyor",
            "CountingFileHash": "Dosya hash'i hesaplanıyor",
            "ClearingCache": "ÖnBytesellek temizleniyor",
            "DataWeight": "Veri ağırlığı %sBytesayt.",
            "BlocksCount": "Byteslok sayısı: ",
            "DataTransferSpeed": "Yükleme hızı: %sBytes/sn",
            "MergingSpeed": "Bytesirleştirme hızı: %sBytes/sn",
            "DataReceivedWeight": "Alınan paketlerin ağırlığı %sBytesayt.",
            "YouCanDoItBytesetter": "Daha iyi yapaBytesilirsin.",
            "Need": "Gerekli"
        },
    }
    units = {
        "ru": {
            "Exa": "Экса",
            "Yotta": "Йотта",
            "Ronna": "Ронна",
            "Zetta": "Зетта",
            "Peta": "Пета",
            "Tera": "Тера",
            "Giga": "Гига",
            "Hega": "Иега",
            "Kilo": "Кило"
        },
        "en": {
            "Exa": "Exa",
            "Yotta": "Yotta",
            "Ronna": "Ronna",
            "Zetta": "Zetta",
            "Peta": "Peta",
            "Tera": "Tera",
            "Giga": "Giga",
            "Hega": "Hega",
            "Kilo": "Kilo"
        },
        "it": {
            "Exa": "Exa",
            "Yotta": "Yotta",
            "Ronna": "Ronna",
            "Zetta": "Zetta",
            "Peta": "Peta",
            "Tera": "Tera",
            "Giga": "Giga",
            "Hega": "Hega",
            "Kilo": "Chilo"
        },
        "de": {
            "Exa": "Exa",
            "Yotta": "Yotta",
            "Ronna": "Ronna",
            "Zetta": "Zetta",
            "Peta": "Peta",
            "Tera": "Tera",
            "Giga": "Giga",
            "Hega": "Hega",
            "Kilo": "Kilo"
        },
        "ja": {
            "Exa": "エクサ",
            "Yotta": "ヨタ",
            "Ronna": "ロンナ",
            "Zetta": "ゼタ",
            "Peta": "ペタ",
            "Tera": "テラ",
            "Giga": "ギガ",
            "Hega": "ヘガ",
            "Kilo": "キロ"
        },
        "zh": {
            "Exa": "埃克萨",
            "Yotta": "约塔",
            "Ronna": "荣纳",
            "Zetta": "泽塔",
            "Peta": "佩塔",
            "Tera": "泰拉",
            "Giga": "吉",
            "Hega": "赫加",
            "Kilo": "千"
        },
        "ko": {
            "Exa": "엑사",
            "Yotta": "요타",
            "Ronna": "론나",
            "Zetta": "제타",
            "Peta": "페타",
            "Tera": "테라",
            "Giga": "기가",
            "Hega": "헤가",
            "Kilo": "킬로"
        },
        "hi": {
            "Exa": "एक्सा",
            "Yotta": "योत्ता",
            "Ronna": "रोन्ना",
            "Zetta": "ज़ेटा",
            "Peta": "पेटा",
            "Tera": "टेरा",
            "Giga": "गीगा",
            "Hega": "हेगा",
            "Kilo": "किलो"
        },
        "ar": {
            "Exa": "إكسا",
            "Yotta": "يوتا",
            "Ronna": "رونا",
            "Zetta": "زيتا",
            "Peta": "بيتا",
            "Tera": "تيرا",
            "Giga": "جيجا",
            "Hega": "هيغا",
            "Kilo": "كيلو"
        }
    }


    def __init__(self, language="en"):
        if language not in self.frases.keys():
            print(f"Language '{language}' not supported. Defaulting to 'en'.")
            self.language = "en"
        else:
            self.language = language

    def get_language(self):
        return self.language

    def get_text(self, text_name):
        lang_dict = self.frases.get(self.language, self.frases["en"])  # По умолчанию используем английский

        # Возвращаем текст по заданному идентификатору
        return lang_dict.get(text_name, "Text not found")  # Возвращаем сообщение, если текст не найден

    def get_unit(self, unit_name):
        lang_dict = self.units.get(self.language, self.units["en"])  # По умолчанию используем английский
        return lang_dict.get(unit_name, "Unit not found")  # Возвращаем сообщение, если единица не найдена

